name: Publish fppy-learn to PYPI
on: 
  pull_request:
    branches:
      - main # 仅当pull request到main的时候操作
jobs:
  Initialization-Actions:
    runs-on: ubuntu-latest # 指定系统
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
