name: Publish fppy-learn to PYPI
on: 
  push:
    branches:
      - main # 仅当pull request到main的时候操作
jobs:
  Initialization-Actions:
    runs-on: ubuntu-latest # 指定系统
    steps:
      - uses: actions/checkout@v2
      - name: check list
        run: ls -all
      - name: install poetry
        run: pip install poetry
      - name: install all dependencies
        run: poetry install
      - name: build
        run: poetry build
      - name: publish
        run: poetry publish --username 3gee --password ${{ secrets.PYPI_TOKEN }}