name: Publish fppy-learn to PYPI
on: 
  pull_request:
    branches:
      - main # 仅当pull request到main的时候操作
jobs:
  Initialization-Actions:
    runs-on: ubuntu-latest # 指定系统
    steps:
      - uses: actions/checkout@v2
      - name: Environment setup
        working-directory: ./
        with:
          python_version: "3.7.1"
          poetry_version: "==1.1.12"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
      - run: pip install poetry
      - run: poetry install
      - run: poetry build
      - run: poetry publish